file_type: csv
dataset_name: train_df_new
file_name: train_new
inbound_delimiter: ","
outbound_delimiter: "|"
skip_leading_rows: 1
columns: 
    - customer_ID
    - S_2
    - P_2
    - D_39
    - B_1
    - B_2
